on:
  push:
    branches:
      - main
    paths:
      - 'Blogwasm/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Blogwasm/**'
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 'PROD'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLOGWASM }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Blogwasm"
          output_location: "Blogwasm/bin/Release/net8.0"